# Generated by Django 5.0.6 on 2024-12-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionteacher'),
        ),
    ]
