# Generated by Django 5.0.6 on 2024-12-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_alter_availabletime_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionteacher'),
        ),
    ]
